### ISSUE TITLE
Add Retry annotation

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-library#132]
cc @jeffhollan @TsuyoshiUshio @amamounelsayed 

PR: https://github.com/Azure/azure-webjobs-sdk/pull/2463 added support for function execution retries 

Tracking item to add annotations

Note: this would require updating mvn plugin to consume the new library

**Comment by jeffhollan** [comment]
@apawast this may be a good item to drop on our GitHub project to close out this feature

**Comment by amamounelsayed** [comment]
Thank you so much @pragnagopa. We will priories this work item.

**Comment by pragnagopa** [comment]
Tagging @casper-79 to track progress

**Comment by casper-79** [comment]
Hi @amamounelsayed

Do you have an estimate on when the updated mvn plugin will be available? We are working on an application that really needs the retry annotation ..

**Comment by casper-79** [comment]
Hi @jeffhollan @TsuyoshiUshio @amamounelsayed

Can any of you provide guidance on when the retry annotation will be ready to use?

**Comment by jeffhollan** [comment]
The base implementation in the next day or so

**Comment by amamounelsayed** [comment]
Thank you @casper-79 With the base implementation, you can add manually in the host.json or function.json the retry tag, this will unblock you. Meanwhile we will add the annotation ETA mid November. We will update in case any delays.

**Comment by casper-79** [comment]
Thanks @amamounelsayed 

Is there any documentation you can point me to? I have tried to figure out how to do it based on this [commit](https://github.com/Azure/azure-functions-host/pull/6706/commits/3d2ba6a04e1149ad5756fb3d2616b77004aacf92), but I am not exactly sure I did it right. Using a host.json file as seen below, I would expect failing messages to be retried in 5s, 10s, 20s, 40s, 80s ...?

`{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "retry": {
    "strategy": "exponentialBackoff",
    "maxRetryCount": 6,
    "delayInterval": "00:00:05"
  }
}`

**Comment by pragnagopa** [comment]
We will be posting documentation for using `retry` soon. Please hold off using the feature until then. Docs will be updated as soon as the functions runtime version that supports this feature is rolled out to all regions in production.

**Comment by pragnagopa** [comment]
@casper-79  - Docs are now public
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=java

**Comment by casper-79** [comment]
Thanks @pragnagopa  

Will this also work for our Python functions running on Linux instances?

Best regards,

Casper

**Comment by casper-79** [comment]
Hello again @pragnagopa

I have tested the retry functionality today and seen the exponential retry strategy in action. I am also seeing some very strange behaviour, however. As I understand the documentation the retry strategy is implemented on the function instance itself, rather than storing the delivery state on the queue. I am seeing what I believe is side effects of this approach. My experiments center around submitting poisonous messages that will always fail onto a queue consumed by a Java azure function. The function uses a retry strategy defined in host.json as seen below:

```
"retry":{
  "strategy":"exponentialBackoff",
  "maxRetryCount":6,
  "minimumInterval":"00:00:10",
  "maximumInterval":"00:05:00"
}
```

(1) Processing of poisonous messages does not always show up in the Application Insights and the "monitor" section of Azure functions. When I use the Azure portal to peek look at test messages I can tell DeliveryCount has gone up by 1, but more often than not there is no trace of the failed execution that increased the counter.

(2) Azure function instances are short lived, thereby affecting the useful range of the parameters in the retry configuration parameters. Can you provide guidance on what will work in practice? I am guessing you will run into problems if you set maximumInterval to 24 hours and retryCount to 30 in my host.json? 

(3) What is the recommended approach for dead lettering? The only solution I can think of is to set maxDeliveryCount=1 on the queue, but this will only work if all retry attempts of your strategy can be be performed within the typical lifetime of an instance. Otherwise, I guess the message will be retried for ever.

Regards,

Casper

**Comment by jeffhollan** [comment]
Gonna reply to this in another thread as not related to this issue, though arguably of these points may justify their own issue (specifically the non-durability of the current implementation) - but for now let's move this conversation here: https://github.com/Azure/azure-webjobs-sdk/issues/2595

**Comment by TsuyoshiUshio** [comment]
Sorry for being late. I also consider to the Kafka extension. https://github.com/Azure/azure-functions-kafka-extension/issues/122

**Comment by m-moris** [comment]
When do you plan to implement retry annotation? Is there any progress?

Thanks.

**Comment by amamounelsayed** [comment]
It has been release, https://github.com/Azure/azure-functions-java-library/releases/tag/1.4.2
https://github.com/Azure/azure-functions-java-library/releases/tag/1.4.2-SNAPSHOT

Thank you
